basePath: /
definitions:
  dto.Message:
    properties:
      message:
        type: string
    type: object
  dto.ResponseOutput:
    properties:
      bid:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: antoniofmoliveira@gmail.com
    name: Antonio Francisco Macedo de Oliveira
    url: http://github.com/antoniofmoliveira/fullcycle-client-server-api
  description: Api para buscar e guardar cotação do dólar
  license:
    name: MIT
    url: http://github.com/antoniofmoliveira/fullcycle-client-server-api/license.txt
  termsOfService: http://swagger.io/terms/
  title: Api Cotação do Dólar
  version: "1.0"
paths:
  /cotacao/:
    get:
      consumes:
      - application/json
      description: Get a exchange rate for dollar
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseOutput'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Message'
        "504":
          description: Gateway Timeout
          schema:
            $ref: '#/definitions/dto.Message'
      summary: Get a exchange rate for dollar
      tags:
      - exchange rate
swagger: "2.0"
